package Railway.Functionalities.Routes;

public class CreateStationsFromList {
    String[] stationNames = {
            "Central",
            "Union",
            "Grand Central",
            "Penn",
            "King's Cross",
            "Paddington",
            "Victoria",
            "Waterloo",
            "Saint Pancras",
            "Euston",
            "Liverpool Street",
            "Charing Cross",
            "Marylebone",
            "Fenchurch Street",
            "Glasgow Central",
            "Edinburgh Waverley",
            "Birmingham New Street",
            "Manchester Piccadilly",
            "Leeds",
            "Bristol Temple Meads",
            "Newcastle Central",
            "Sheffield",
            "Nottingham",
            "Cardiff Central",
            "Reading",
            "Brighton",
            "Liverpool Lime Street",
            "London Bridge",
            "London Victoria",
            "London Waterloo",
            "London Paddington",
            "London Euston",
            "London King's Cross",
            "London Saint Pancras",
            "London Liverpool Street",
            "London Charing Cross",
            "London Marylebone",
            "London Fenchurch Street",
            "London Glasgow Central",
            "Edinburgh Waverley",
            "Birmingham New Street",
            "Manchester Piccadilly",
            "Leeds",
            "Bristol Temple Meads",
            "Newcastle Central",
            "Sheffield",
            "Nottingham",
            "Cardiff Central",
            "Reading",
            "Brighton",
            "Liverpool Lime Street",
            "London Bridge",
            "London Victoria",
            "London Waterloo",
            "London Paddington",
            "London Euston",
            "London King's Cross",
            "London Saint Pancras",
            "London Liverpool Street",
            "London Charing Cross",
            "London Marylebone",
            "London Fenchurch Street",
            "London Glasgow Central",
            "Edinburgh Waverley",
            "Birmingham New Street",
            "Manchester Piccadilly",
            "Leeds",
            "Bristol Temple Meads",
            "Newcastle Central",
            "Sheffield",
            "Nottingham",
            "Cardiff Central",
            "Reading",
            "Brighton",
            "Liverpool Lime Street",
            "London Bridge",
            "London Victoria",
            "London Waterloo",
            "London Paddington",
            "London Euston",
            "London King's Cross",
            "London Saint Pancras",
            "London Liverpool Street",
            "London Charing Cross",
            "London Marylebone",
            "London Fenchurch Street",
            "London Glasgow Central",
            "Edinburgh Waverley",
            "Birmingham New Street",
            "Manchester Piccadilly",
            "Leeds",
            "Bristol Temple Meads",
            "Newcastle Central",
            "Sheffield",
            "Nottingham",
            "Cardiff Central",
            "Reading",
            "Brighton",
            "Liverpool Lime Street",
            "London Bridge"
    };
    public Station[] CreateStations() {
        Station[] stations = new Station[stationNames.length];
        for (int i = 0; i < stationNames.length; i++) {
            stations[i] = new Station(stationNames[i]);
        }
        return stations;
    }
}
